### ISSUE TITLE
Error: Failed to apply catalog: Parameter mode failed on File - Ubuntu 16

### ISSUE THREAD

**Issue by aryeharmon** [scottsb/puppet-clustersync#4]
Error: Failed to apply catalog: Parameter mode failed on File[/var/log/lsyncd]: The file mode specification must be a string, not 'Integer' at /etc/puppetlabs/code/environments/production/modules/lsyncd/manifests/init.pp:49

**Comment by scottsb** [comment]
This is actually a bug with the lsyncd module that this module depends on. It appears there is an unmerged pull request to fix it: thias/puppet-lsyncd#3. Since it's over a year old, I'm guessing that thias isn't maintaining his module anymore. If someone forks that module and adds to Puppet Forge, then I'll update the dependency here. I'll leave this issue open for the moment.

I haven't tested it, but a workaround may be to uninstall your current version of the module from Puppet Forge and [reinstall](https://puppet.com/docs/puppet/4.10/modules_installing.html#install-from-a-release-tarball) a tarball of the [patched version](https://github.com/nerdlich/puppet-lsyncd/archive/7114f5c0352871c79b8f9c0a5d84f7a2f843a89b.tar.gz).

**Comment by scottsb** [comment]
Actually, never mind. On closer inspection, it looks like that lsyncd pull request isn't strictly necessary. It would only be a protection if the wrong value was being passed into the class. The default provided in the lsyncd module was already correct. However, the default I set in my wrapper here was wrong. Will correct now.
